# Autogenerated wrapper script for CUDD_jll for aarch64-linux-gnu-cxx11
export libcudd

JLLWrappers.@generate_wrapper_header("CUDD")
JLLWrappers.@declare_library_product(libcudd, "libcudd-3.0.0.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcudd,
        "lib/libcudd.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
