# Autogenerated wrapper script for CUDD_jll for i686-w64-mingw32-cxx03
export libcudd

JLLWrappers.@generate_wrapper_header("CUDD")
JLLWrappers.@declare_library_product(libcudd, "libcudd-3-0-0-0.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcudd,
        "bin\\libcudd-3-0-0-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
