# Autogenerated wrapper script for CUDD_jll for x86_64-apple-darwin
export libcudd

JLLWrappers.@generate_wrapper_header("CUDD")
JLLWrappers.@declare_library_product(libcudd, "@rpath/libcudd-3.0.0.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcudd,
        "lib/libcudd.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
